config/routes.rb
Pledger::Application.routes.draw do

  resources :trackees do
    resources :pledges
  end
  root :to => redirect('/trackees')

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

  belongs_to :trackee
  attr_protected :trackee_id
  attr_accessible :title, :description, :citation

end

app/models/trackee.rb
class Trackee < ActiveRecord::Base

  has_many :pledges
  attr_accessible :first_name, :last_name, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  #TODO create pledge function
  #figure out how to add trackee id and then save
  
  #try this
  #@order = @customer.orders.create(order_date: Time.now)
  #http://guides.rubyonrails.org/association_basics.html

  def new

    @trackee = params[:trackee_id]

  end

  def create

    debugger
    @trackee = params[:trackee_id]
    @pledge = Pledge.create!(params[:pledge])
    flash[:success] = 'Pledge added!'
    redirect_to trackee_path(@trackee)

  end

end

app/controllers/trackees_controller.rb
class TrackeesController < ApplicationController

  def index

    @trackees = Trackee.last(10).reverse

  end

  def new

  end

  def create

    @trackee = Trackee.create!(params[:trackee])
    flash[:success] = "#{@trackee.first_name} #{@trackee.last_name} was created!"
    redirect_to trackees_path

  end

  def show

    id = params[:id]
    if (@trackee = Trackee.find_by_id(id))

    else
      @trackee = Trackee.new
      flash[:error] = "Oops! We can't find that person!"
    end

    def edit

      id = params[:id]
      if(@trackee = Trackee.find_by_id(id))

      else
        flash[:error] = "Oops! We can't find that person!"
        redirect_to trackees_path
      end

    end

    def update

      id = params[:id]
      @trackee = Trackee.find_by_id(id)
      @trackee.update_attributes!(params[:trackee])
      flash[:success] = "#{@trackee.first_name} #{@trackee.last_name} has been updated!"
      redirect_to trackee_path(@trackee)

    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)

    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end

  end

end

app/views/layouts/_flash_display.html.haml
- flash.each do |key, value|
  %div{:class => (flash_class(key))}
    = value

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Bootstrap Template
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'bootstrap.css'
    = stylesheet_link_tag 'bootstrap-responsive.css'

    =csrf_meta_tags

    = javascript_include_tag 'application'

  %body
    %div.navbar.navbar-inverse.navbar-fixed-top{:role => 'navigation'}
      %div.navbar-inner
        %div.container
          %button.btn-navbar{:type => 'button', 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => '#'} Project Name
          %div.nav-collapse.collapse
            %ul.nav
              %li{:class => "#{'active' if current_page?(trackees_path)}"}
                %a{:href => root_path} Home
              %li
                %a{:href => '#'} About
              %li
                %a{:href => '#'} Contact
    = yield

app/views/pledges/_pledge_form.html.haml
= label :pledge, 'Title'
= text_field :pledge, 'title'

= label :pledge, 'Description'
= text_area(:pledge, 'description', class: 'input-xxlarge', rows: '5')

= label :pledge, 'Citation'
= text_field :pledge, 'citation'
%br

app/views/pledges/new.html.haml
%div.container
  %h1 Create Pledge

  = render :partial => 'layouts/flash_display'

  = form_tag trackee_pledges_path do

    = render :partial => 'pledge_form'
    = submit_tag 'Add Pledge'

  = link_to "Back to Profile", trackee_path(@trackee)

app/views/trackees/_trackee_form.html.haml
= label :trackee, :first_name, 'First Name'
= text_field :trackee, 'first_name'

= label :trackee, :last_name, 'Last Name'
= text_field :trackee, 'last_name'

= label :trackee, :description, 'Description'
= text_area(:trackee, :description, class: 'input-xxlarge', rows: '5')
%br

app/views/trackees/edit.html.haml
%div.container
  %h1 Edit

  = render :partial => 'layouts/flash_display'

  = form_tag trackee_path, :method => 'put' do
    = render :partial => 'trackee_form'
    = submit_tag 'Save Changes'

  = link_to 'Back to Profile', trackee_path(@trackee)

app/views/trackees/index.html.haml
%div.container
  %h1 trackees

  = render :partial => 'layouts/flash_display'

  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th First
        %th Last
        %th Profile
    %tbody
      - @trackees.each do |trackee|
        %tr
          %td= trackee.first_name
          %td= trackee.last_name
          %td= link_to "View", trackee_path(trackee)

  = link_to 'Add new trackee', new_trackee_path

app/views/trackees/new.html.haml
%div.container
  %h1 Create New Trackee

  = render :partial => 'layouts/flash_display'

  = form_tag trackees_path do
    = render :partial => 'trackee_form'
    = submit_tag 'Save Trackee'

app/views/trackees/show.html.haml
%div.container
  %h1 #{@trackee.first_name} #{@trackee.last_name}

  = render :partial => 'layouts/flash_display'

  %p
    #{@trackee.description}
  = link_to "Back to List", trackees_path
  = link_to "Edit Profile", edit_trackee_path(@trackee)
  = link_to "Add Pledge", new_trackee_pledge_path(@trackee)